# Generated by Django 5.1.5 on 2025-03-05 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_is_featured_product_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=9, max_digits=9, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
    ]
