# Generated by Django 5.1.5 on 2025-03-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='category',
            field=models.CharField(choices=[('School', 'School/College Bag'), ('Luggage', 'Luggage'), ('Handbag', 'Hand Bag'), ('Duffle', 'Duffle Bag'), ('Purse', 'Purse'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
