# Generated by Django 5.1.5 on 2025-03-06 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_bag_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='category',
        ),
    ]
