# Generated by Django 5.1.5 on 2025-03-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_bag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='category',
            field=models.CharField(choices=[('Shoulder Bag', 'Shoulder Bag'), ('Luggage', 'Luggage'), ('Duffle', 'Duffle'), ('Purse', 'Purse'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
